# Random Forest for Classification

 Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing Dataset

In [2]:
dataset = pd.read_csv("bill_authentication.csv")


In [3]:
dataset.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0



```
# This is formatted as code
```

Preparing Data For Training

In [4]:
X = dataset.iloc[:, 0:4].values
y = dataset.iloc[:, 4].values

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)



Feature Scaling

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


Training the Algorithm

In [7]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

Evaluating the Algorithm

In [8]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix:
[[154   3]
 [  2 116]]


In [9]:
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       157
           1       0.97      0.98      0.98       118

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275



In [10]:
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Accuracy: 0.9818181818181818



**-----------------------------------------------------------------------------------------**

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [12]:
dataset1 = pd.read_csv("bill_authentication.csv")

In [13]:
dataset1.shape

(1372, 5)

In [14]:
dataset1.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [15]:
X = dataset1.drop('Class', axis=1)
y = dataset1['Class']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test1 = train_test_split(X, y, test_size=0.20)


In [17]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
y_pred1 = classifier.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test1, y_pred1))
print(classification_report(y_test1, y_pred1))

[[151   3]
 [  1 120]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       154
           1       0.98      0.99      0.98       121

    accuracy                           0.99       275
   macro avg       0.98      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [20]:
result1 = accuracy_score(y_test1,y_pred1)
print("Accuracy:",result1)

Accuracy: 0.9854545454545455



**-----------------------------------------------------------------------------------------**

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [22]:
bankdata = pd.read_csv("bill_authentication.csv")

In [23]:
bankdata.shape

(1372, 5)

In [24]:
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [25]:
X = bankdata.drop('Class', axis=1)
y = bankdata['Class']

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test2 = train_test_split(X, y, test_size = 0.20)


In [27]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)



SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [28]:
y_pred2 = svclassifier.predict(X_test)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test2,y_pred2))
print(classification_report(y_test2,y_pred2))

[[151   4]
 [  2 118]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       155
           1       0.97      0.98      0.98       120

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275



In [30]:
result3 = accuracy_score(y_test2,y_pred2)
print("Accuracy:",result3)

Accuracy: 0.9781818181818182



**-----------------------------------------------------------------------------------------**

In [31]:
dataset4=pd.read_csv("bill_authentication.csv")
X=dataset4.drop('Class',axis=1)
y=dataset4['Class']


In [32]:
from sklearn.model_selection import train_test_split
X_train4,X_test4,y_train4,y_test4=train_test_split(X,y,test_size=0.20)

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
model = LogisticRegression(solver='lbfgs', max_iter=2000, multi_class='auto')

In [35]:
model.fit(X_train4,y_train4)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
model.score(X_test4,y_test4)

0.9890909090909091


**-----------------------------------------------------------------------------------------**

In [37]:
X_train5,X_test5,y_train5,y_test5=train_test_split(X,y,test_size=0.20)

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
regr = LinearRegression()

In [39]:
regr.fit(np.array(X_train5), y_train5)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [40]:
preds = regr.predict(np.array(X_test5))

In [41]:
mean_squared_error(y_test5, preds) ** 0.5

0.17651300091734032

In [43]:
model.score(X_test5,y_test5)

0.9927272727272727