In [1]:
import pandas as pd
import numpy as np

In [2]:
xl = pd.ExcelFile('ex3d1.xlsx')
df = pd.read_excel(xl, 'X', header=None)
df.head()

0    1    2    3    4    5    6    ...  393  394  395  396  397  398  399
0    0    0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0    0
1    0    0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0    0
2    0    0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0    0
3    0    0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0    0
4    0    0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0    0

[5 rows x 400 columns]

In [3]:
y = pd.read_excel(xl,'y',header = None)
y.head(5)

0
0  10
1  10
2  10
3  10
4  10

In [4]:
df = df.iloc[1:]

In [5]:
y = y.iloc[:, 0]

In [6]:
y[:5]

0    10
1    10
2    10
3    10
4    10
Name: 0, dtype: int64

In [7]:
y.unique()

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [8]:
y1 = np.zeros([df.shape[0], len(y.unique())])
y1 = pd.DataFrame(y1)

In [9]:
len(df)

4999

In [10]:
len(y)

5000

In [11]:
y.unique()

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [12]:
for i in range(0, len(y.unique())):
    for j in range(0, len(y1)):
        if y[j] == y.unique()[i]:
            y1.iloc[j, i] = 1
        else: 
            y1.iloc[j, i] = 0
y1.head()           

0    1    2    3    4    5    6    7    8    9
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [13]:
y1.tail()

0    1    2    3    4    5    6    7    8    9
4994  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [14]:
y1.shape

(4999, 10)

In [15]:
theta = np.zeros([df.shape[1]+1, y1.shape[1]])

In [16]:
theta.shape

(401, 10)

In [17]:
theta.shape[0]

401

In [18]:
X = pd.concat([pd.Series(1, index=df.index, name='00'), df], axis=1)

In [19]:
X.shape

(4999, 401)

In [20]:
theta = np.ones(df.shape[1]+1)
def hypothesis(theta, X):
    return 1 / (1 + np.exp(-(np.dot(theta, X.T)))) - 0.0000001

In [21]:
theta.shape

(401,)

In [22]:
h = hypothesis(theta, X)

In [23]:
def cost(X, y, theta):
    y1 = hypothesis(X, theta)
    return -(1/len(X)) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))    

In [24]:
theta = pd.DataFrame(theta)

In [25]:
type(theta.iloc[:,0])

pandas.core.series.Series

In [26]:
def gradient_descent(X, y, theta, alpha, epochs):
    m = len(X)
    #cost = [[] for i in range(10)]
    for i in range(0, epochs):
        for j in range(0, 10):
            theta = pd.DataFrame(theta)
            h = hypothesis(theta.iloc[:,j], X)
            for k in range(0, theta.shape[0]):
                theta.iloc[k, j] -= (alpha/m) * np.sum((h-y.iloc[:, j])*X.iloc[:, k])
            theta = pd.DataFrame(theta)
            #c =cost(X, y.iloc[:, j], theta.iloc[:,j])
            #cost[j].append(c)
    return theta           

In [27]:
theta = np.zeros([df.shape[1]+1, y1.shape[1]])
theta = gradient_descent(X, y1, theta, 0.02, 1500)

In [28]:
theta

0             1  ...             8             9
0   -4.689556e-01 -5.798220e-02  ... -6.786367e-01 -3.547820e-01
1    0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
2    0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
3   -1.156707e-07  2.438578e-06  ... -6.315622e-07 -4.213735e-07
4    1.388053e-06 -2.190558e-05  ...  6.356410e-06  7.746520e-06
..            ...           ...  ...           ...           ...
396  7.524218e-05  7.647467e-05  ...  1.626417e-04  1.298702e-05
397  3.758661e-05 -9.375980e-06  ...  4.458031e-05  1.387648e-05
398 -1.349297e-05 -5.715428e-07  ... -1.645026e-05 -2.508244e-06
399  7.667924e-07  7.846159e-08  ...  8.980578e-07  8.376091e-08
400  0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00

[401 rows x 10 columns]

In [29]:
def predict(X, y):
    #theta1 = gradient_descent(X, y, theta, alpha, epochs)
    accuracy = 0
    for i in range(10):
        h = hypothesis(theta1.iloc[:,j], X)
        for n in range(0, len(h)):
            if h[n] >= 0.5 and y1.iloc[n, i] == 1:
                accuracy += 1
            elif h[n] < 0.5 and y1.iloc[n, i] == 0:
                accuracy += 1
    return accuracy       
        

In [30]:
theta = pd.DataFrame(theta)
hypothesis(theta.iloc[:,9], X)

array([1.23417063e-04, 2.67843965e-04, 8.41147843e-05, ...,
       5.80221347e-01, 2.07531540e-01, 4.01198563e-03])

In [31]:
output = []
for i in range(0, 10):
    theta1 = pd.DataFrame(theta)
    h = hypothesis(theta1.iloc[:,i], X)
    output.append(h)
output=pd.DataFrame(output)

In [32]:
output

0         1         2     ...      4996      4997      4998
0  0.996469  0.010577  0.601812  ...  0.001574  0.000321  0.173809
1  0.000066  0.000008  0.000004  ...  0.008508  0.000061  0.000008
2  0.000204  0.000316  0.001053  ...  0.005179  0.000005  0.024387
3  0.000801  0.000792  0.000230  ...  0.064561  0.000001  0.000127
4  0.000139  0.000059  0.000113  ...  0.276236  0.087315  0.035951
5  0.075771  0.017214  0.005847  ...  0.190739  0.009224  0.000151
6  0.000161  0.004188  0.011677  ...  0.059126  0.000190  0.009331
7  0.002439  0.000570  0.000653  ...  0.006254  0.093345  0.089564
8  0.000146  0.028730  0.000426  ...  0.032581  0.002624  0.008259
9  0.000123  0.000268  0.000084  ...  0.580221  0.207532  0.004012

[10 rows x 4999 columns]

In [33]:
output.iloc[2, 50]

0.13288621052505406

In [34]:
accuracy = 0
for col in range(0, 10):
    for row in range(len(y1)):
        if y1.iloc[row, col] == 1 and output.iloc[col, row] >= 0.5:
            accuracy += 1
accuracy

3602

In [35]:
accuracy= accuracy/len(X)

In [36]:
accuracy

0.7205441088217643